Origin/feature measurement
BCFCODE/FocusToDo-Speed-Tracker pull request #27
Opened 2023-11-07 09:24 UTC by majidbabakh

اسم branch غلط املایی داشت اصلاحش کردم
فولدر های node_modules و vscode انداختم تو .gitignore 
از فانکشن dateOfMeasurement هم new Date() را return کردم ولی test برام جواب نمیده ارور میده 
اگه مشکلی داشت بگو

2023-11-07 10:26 UTC, BCFCODE commented
خط زمان رو دنبال کن، قبل از شروع حتما log بگیر و شاخه ها رو ببین
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/469c350f-8286-411a-8072-cb90c730940c)
جایی که ایستادی هنوز من تستی رو ننوشته بودم!

2023-11-07 10:29 UTC, BCFCODE commented
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/22773dfb-964f-4188-8b15-d7bb8727acf9)
با عنوان یک عادت خوب تمام این موارد رو در هر پول مشخص کن

2023-11-07 10:39 UTC, BCFCODE commented on .gitignore
> +.vscode
این فایل دیشب ادد شده، برنچ از جای صحیحی ایجاد نشده

2023-11-07 10:39 UTC, BCFCODE commented on .gitignore
> +.vscode
از اینجا ببعد بابت هر کامنت باید یدونه ناتیفیکیشن روی گوشی دریافت کنی چک کن و اطلاع بده

2023-11-07 10:46 UTC, BCFCODE commented
Did you see that? 
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/91122157-69b5-4041-8419-7bda628d427f)

2023-11-07 10:46 UTC, BCFCODE commented
> اسم branch غلط املایی داشت اصلاحش کردم فولدر های node_modules و vscode انداختم تو .gitignore از فانکشن dateOfMeasurement هم new Date() را return کردم ولی test برام جواب نمیده ارور میده اگه مشکلی داشت بگو

ولی بالاخره داستان رو متوجه شدی دمت گرم

2023-11-07 12:57 UTC, BCFCODE requested changes
خظ زمانی رو اوکی کن، این مال گذشته است

2023-11-07 12:58 UTC, majidbabakh commented on .gitignore
> +.vscode
نوتی میاد ولی برا هر کامنت فک نکنم

2023-11-07 12:59 UTC, majidbabakh commented
> ظ زمانی رو ا

زمانش چیه؟

2023-11-07 13:00 UTC, BCFCODE commented on .gitignore
> +.vscode
روی کامنت های پول ریکوئست واس هر کدومش میاد، دو تا بیشتر نذاشتم تا الان...

2023-11-07 13:02 UTC, BCFCODE commented
هر سوالی داشتی تاپیک جدید باز کن که قاطی پاتی نشه و قابل سرچ باشه بعدا و بپرس

2023-11-07 13:12 UTC, BCFCODE commented on .gitignore
> +.vscode
الان ببین واس این نوتی می گی ری؟

2023-11-07 13:30 UTC, BCFCODE commented on app.js
> +};
مثلا روی این خط کد من این پیام رو نوشتم، ببین نوتی میاد؟

2023-11-07 16:05 UTC, majidbabakh commented on app.js
> +};
Nop

2023-11-07 16:52 UTC, BCFCODE commented on app.js
> +};
احتمال داره این رو در آپدیت های آتی اپ اندرویدش حل کنن

2023-11-08 12:55 UTC, majidbabakh commented
مشکل این pull request چیه که merge نکردی؟

2023-11-08 20:32 UTC, BCFCODE commented
> مشکل این pull request چیه که merge نکردی؟

به یاد داری زمانی که این برنچ رو ساختی؟ به یاد داری که از چه نقطه (commit) این برنچ تشکیل شد؟ 
git log --oneline --graph --all
رو بزن و شات اش رو ارسال کن
احتمال می دم اگر اکتیو با هم مرورش کنیم راحت تر متوجه اش میشی، اما اگر حس می کنی که مستقیم برم سر اصل مطلب و خودم شات بفرستم بهتره اون شکلی هم می تونیم
آنچه که قراره مرور بشه: داستان اینه که زمانی که این برنچ رو ساختی و روش در حال کار بودی، من چندین کمیت روی main یعنی برنچ اصلی جلو رفتم
اینجا تو موازی با من درحال کار بودی
حالا من روی main تست ها رو نوشتم و ...، همین طور گیت ایگنور و ... رو اوکی کردم
بعد تو این پول ریکوئست رو دادی
حالا چی داریم؟
من که روی برنچ اصلی پیش روی کردم (پیشروی در خط زمانی) و تو که موازی روی برنچ دیگه در حال اضافه کردن گیت ایگنور و حل مسئله بدون تست بودی که مشکل رو هم مطرح کردی گفتی نمی دونی چرا تست بهت جواب نداده
حالا اگر گفتی چه اتفاقی افتاده و باید چکار کنی؟

2023-11-09 09:05 UTC, closed without merging