show current time in index.html
BCFCODE/FocusToDo-Speed-Tracker pull request #35
Opened 2023-11-11 14:15 UTC by majidbabakh

ببین همونه که مدنظرته

2023-11-11 20:19 UTC, BCFCODE requested changes
موارد روی خطوط مربوطه اضافه شد

2023-11-11 20:19 UTC, BCFCODE commented on app.js
> +document.getElementById(
اینم فک کنم اولین کامنت روی کد
می تونی همین رو با جی کوئری انجامش بدی بجای دام؟

2023-11-11 20:19 UTC, BCFCODE commented on app.js
کلا داری راه می افتی، بنظرم با سرعت زیادی پیش خواهی رفت بزودی

2023-11-11 20:19 UTC, BCFCODE commented
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/76dd4098-77fd-4a04-9c6b-b880d146cc0c)
این بخش نشون میده که درخواست برای تغییر دارم

2023-11-11 20:52 UTC, majidbabakh commented
> ![image](https://user-images.githubusercontent.com/78473407/282263787-76dd4098-77fd-4a04-9c6b-b880d146cc0c.png) این بخش نشون میده که درخواست برای تغییر دارم

چیو باید تغییر بدم؟ درخواست تغییرو از کجا باید ببینم؟

2023-11-11 20:54 UTC, BCFCODE commented
> > ![image](https://user-images.githubusercontent.com/78473407/282263787-76dd4098-77fd-4a04-9c6b-b880d146cc0c.png) این بخش نشون میده که درخواست برای تغییر دارم
> 
> چیو باید تغییر بدم؟ درخواست تغییرو از کجا باید ببینم؟

روش کلیک کن
روی خط به خط مواردی که باید انجام بشه کامنت گذاشتم توضیحات ت رو بنویس

2023-11-11 20:56 UTC, BCFCODE commented
> > > ![image](https://user-images.githubusercontent.com/78473407/282263787-76dd4098-77fd-4a04-9c6b-b880d146cc0c.png) این بخش نشون میده که درخواست برای تغییر دارم
> > 
> > 
> > چیو باید تغییر بدم؟ درخواست تغییرو از کجا باید ببینم؟
> 
> روش کلیک کن روی خط به خط مواردی که باید انجام بشه کامنت گذاشتم توضیحات ت رو بنویس

![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/f038cd78-08b2-47af-a9a3-5020dfaeda53)

2023-11-11 21:02 UTC, BCFCODE requested changes
موارد لازم اعمال بشه

2023-11-12 05:46 UTC, majidbabakh commented on index.html
> -      <br>
> ![image](https://user-images.githubusercontent.com/78473407/282264638-9ebccc9f-f8f5-4685-95db-ca3b0a7745c0.png) فرمت اصلی مون اینه و نباید تغییر کنه یچیزایی مث h2 و غیره رو خارج از تسک اضافه کردی
قصدم تغییر فرمت نبود میخواستم یه تفکیکی بین قسمتا بشه و بتونم قسمت مربوط به زمان select کنم و مقدار را داخلش بذارم

2023-11-12 05:48 UTC, majidbabakh commented on index.html
> +    <script defer src="app.js"></script>
البته defer
چون script داره مستقیم با html کار میکنه باید اول html خونده بشه بعد script تا اول اجزا html براش تعریف بشه

2023-11-12 05:48 UTC, majidbabakh commented on index.html
> +      <h2>
صرفا تفکیک و چیز خاصی نیست میشه تغییرش داد

2023-11-12 05:49 UTC, majidbabakh commented on index.html
> +      <p>
رو سیستم من جواب میده !

2023-11-12 05:49 UTC, majidbabakh commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
قرار نبوده element به صفحه اضافه کنم فقط text اضافه شده پس ...

2023-11-12 07:31 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
In HTML, the defer attribute is used in the <script> element to control the execution timing of a JavaScript file. When you include a script tag with the defer attribute, it indicates to the browser that the script should be executed after the HTML document has been fully parsed. Here's a breakdown of how it works:

Normal Script Execution:

When a browser encounters a <script> tag without the defer attribute, it typically pauses HTML parsing and executes the script immediately.
This can lead to a delay in rendering the rest of the HTML content because the browser has to execute the script before moving on.
Defer Attribute:

When you add the defer attribute to a <script> tag, it tells the browser to continue parsing the HTML document while simultaneously downloading the script in the background.
The script will be executed only after the HTML parsing is complete.
Multiple scripts with the defer attribute will be executed in the order they appear in the HTML document.
Example:

html
Copy code
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Defer Attribute Example</title>
    <script defer src="first.js"></script>
</head>
<body>
    <!-- HTML content -->

    <script defer src="second.js"></script>
</body>
</html>
In this example, first.js will be downloaded and executed after the HTML parsing of the head section, and second.js will be downloaded and executed after the HTML parsing of the body section.

Use Cases:

Using defer is often beneficial for improving page loading performance, especially when scripts are not critical for the initial rendering of the page.
It's commonly used for scripts that manipulate the DOM or interact with elements lower on the page.
Keep in mind that the defer attribute is supported in modern browsers, but it may not behave consistently in older browsers. If you need broader compatibility, you might want to consider alternative methods, such as placing the <script> tag at the end of the <body> element or using the async attribute (though async has a different behavior).

2023-11-12 07:32 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
طبق این توضیحات و اینکه اصلا فعلا کار سنگینی که تاخیر قابل ملاحظه ای ایجاد کنه آیا وجود 
differ
لازم هست؟

2023-11-12 07:34 UTC, BCFCODE commented on index.html
> +      <h2>
> صرفا تفکیک و چیز خاصی نیست میشه تغییرش داد

و پاسخ منطقی و نه احساسی! به سوال چی هست؟ نمیشه که یه چیزی رو تغییر بدیم بعد بگیم چیز خاصی نیست میشه تغییرش داد؟

2023-11-12 07:43 UTC, BCFCODE commented on index.html
> +      <p>
> رو سیستم من جواب میده !

برگردون به حالت اولیه، 
differ 
هم در صورتی که لزومی داشته باشه فقط...
و خب این پاسخی که کمکی بکنه نیست، سیستم هامون باهم فرقی نداره که

2023-11-12 07:43 UTC, BCFCODE commented on index.html
> +      <p>
شات اش رو بفرست بیبنیم مشکل از کجاست

2023-11-12 07:44 UTC, majidbabakh commented on index.html
> +      <h2>
سلیقه ایه!
اگه مطابق میلت نیس میشه تغییرش داد

2023-11-12 07:44 UTC, BCFCODE commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
این سوالات صرفا برای اینه که ازت یاد بگیرم اگر ممکنه یک متن منطقی که اولویت این رو نسبت به دو مورد متداول گفته شده نشون بده واسم بفرست

2023-11-12 07:50 UTC, majidbabakh commented on index.html
> +    <script defer src="app.js"></script>
اصلا کاری به performance ندارم هرچند که استانداردش اینه
ولی تو این مورد تو defer بردار ببین کد برات کار میده یا نه؟
یا باید از defer استفاده کنی یا script ببری آخر html بذاری قشنگ ترش اینکه که از defer استفاده کنی

2023-11-12 07:51 UTC, BCFCODE commented on index.html
> +      <h2>
منطقی: به این دلیل و به این دلیل چون تفکیک لازم بود اعمال شد...
وگرنه باید وقتمون رو صرف فقط و فقط انجام برنامه داشته باشیم
الان تمرکز روی UI نیست برای مراحل بعدی می تونیم روش تمرکز کنیم
حتی یک ثانیه اگر انجام یک کار اضافه باعث بشه یک ثانیه دیر تر پول ریکوئست ارسال بشه، و همینطور بررسی و... اش در دراز مدت زمان زیادی رو خارج از مسیر منتج به هدف در حال صرف کردن هستیم
می تونیم یه 
clone 
بگیریم جدا و روی اون تمرینات رو انجام بدیم و در نهایت پول ریکوئستی که می فرستیم روی برنامه پیش بره

2023-11-12 07:51 UTC, majidbabakh commented on index.html
> +      <p>
اون export { dateOfMeasurement }; تو فایل app.js اگه کامنت کنی کد برات جواب میده اینکه چرا نمیدونم شاید مبحثیه تو تست که من هنوز بلد نیستم

2023-11-12 07:52 UTC, BCFCODE commented on index.html
> +      <h2>
استثنا هم داره، تغییری ایجاد میشه و با عنوان یک ایده مطرح میشه

2023-11-12 07:53 UTC, BCFCODE commented on index.html
> +      <h2>
این موارد رو با عنوان 
Conventions 
اگر موافق باشی می تونیم برای تیم لحاظ کنیم
در نظر داشته باش ده نفر باشند الان که هر ده نفر یک تغییر کوچک اینجوری بخوان بدن و بعد اونی که قراره مرج کنه...

2023-11-12 07:58 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/b2e1338f-47ae-456e-9df0-e0ba2cad3724)
چه دلیلی وجود داره که کار نکنه؟
یه مرور بکن لطفا

2023-11-12 08:00 UTC, BCFCODE commented on index.html
> +      <p>
برات امکانش هست که بدون تغییر در فرمت UI مسئله پیش رو رو حل کنی؟ 
متن و فرمت همون فقط بخش تاریخ داینامیک بشه؟

2023-11-12 08:01 UTC, majidbabakh commented on index.html
> +      <h2>
> منطقی: به این دلیل و به این دلیل چون تفکیک لازم بود اعمال شد... وگرنه باید وقتمون رو صرف فقط و فقط انجام برنامه داشته باشیم الان تمرکز روی UI نیست برای مراحل بعدی می تونیم روش تمرکز کنیم حتی یک ثانیه اگر انجام یک کار اضافه باعث بشه یک ثانیه دیر تر پول ریکوئست ارسال بشه، و همینطور بررسی و... اش در دراز مدت زمان زیادی رو خارج از مسیر منتج به هدف در حال صرف کردن هستیم می تونیم یه clone بگیریم جدا و روی اون تمرینات رو انجام بدیم و در نهایت پول ریکوئستی که می فرستیم روی برنامه پیش بره

حالا اون h2 که در نظر نگیریم (برا این گذاشتم که بدونم این قسمت ثابته تغییر نمیکنه)
قسمت بعدیا را p گذاشتم چون قرار بود select بشن نیاز به یه element داشتم

2023-11-12 08:02 UTC, BCFCODE commented on index.html
> +      <p>
> اون export { dateOfMeasurement }; تو فایل app.js اگه کامنت کنی کد برات جواب میده اینکه چرا نمیدونم شاید مبحثیه تو تست که من هنوز بلد نیستم

درسته اکسپورت فقط برای تست هست

2023-11-12 08:03 UTC, majidbabakh commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
این که میگی اولویت فک نمیکنم اولویتی باشه innerHTML یه قابلیت اضافه داره نسبت به اون

textContents is all text contained by an element and all its children that are for formatting purposes only.
innerText returns all text contained by an element and all its child elements.
innerHtml returns all text, including html tags, that is contained by an element.

2023-11-12 08:05 UTC, majidbabakh commented on index.html
> +      <p>
> برات امکانش هست که بدون تغییر در فرمت UI مسئله پیش رو رو حل کنی؟ متن و فرمت همون فقط بخش تاریخ داینامیک بشه؟

اره اوکیه

2023-11-12 08:06 UTC, BCFCODE commented on index.html
> +      <h2>
مسئله ای نیست خوب کاری کردی، در نهایت توی پول ریکوئست میشه نسخه نهایی رو ارسال کرد
هر المنتی رو که id داره میشه select کرد؟ 
برای اینکه در وقت صرفه جویی بشه میتونیم این پول ریکوئست رو ببندیم و از نقطه قبلی یه دونه برنچ ایجاد کنی فقط تایم رو اوکی کنی که لازم نباشه خودت هم وقت صرف برگردوندن به حالت اولیه کنی

2023-11-12 08:14 UTC, BCFCODE commented
می خوای یه تجربه جدید کنیم این پول ریکوئست رو نمی بندم
پروسه 
review 
رو ادامه میدیم 
یادت نره هر وقت جدید فرستادی 
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/aa51aa25-6ba0-4c7f-af3c-62fc955f7ec5)
این رو بزن تا درخواست مرور برام بیاد 
اینم باعث یادگیری بخش های جدید و قابلیت های گیت هاب میشه

2023-11-12 08:16 UTC, majidbabakh commented
> می خوای یه تجربه جدید کنیم این پول ریکوئست رو نمی بندم پروسه review رو ادامه میدیم یادت نره هر وقت جدید فرستادی ![image](https://user-images.githubusercontent.com/78473407/282286710-aa51aa25-6ba0-4c7f-af3c-62fc955f7ec5.png) این رو بزن تا درخواست مرور برام بیاد اینم باعث یادگیری بخش های جدید و قابلیت های گیت هاب میشه

review زدن ببین شد یا نه؟

2023-11-12 08:19 UTC, BCFCODE commented
> > می خوای یه تجربه جدید کنیم این پول ریکوئست رو نمی بندم پروسه review رو ادامه میدیم یادت نره هر وقت جدید فرستادی ![image](https://user-images.githubusercontent.com/78473407/282286710-aa51aa25-6ba0-4c7f-af3c-62fc955f7ec5.png) این رو بزن تا درخواست مرور برام بیاد اینم باعث یادگیری بخش های جدید و قابلیت های گیت هاب میشه
> 
> review زدن ببین شد یا نه؟

![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/c765d864-84c6-402e-acde-55f125d58cca)

2023-11-12 08:20 UTC, majidbabakh commented on index.html
> +      <h2>
> مسئله ای نیست خوب کاری کردی، در نهایت توی پول ریکوئست میشه نسخه نهایی رو ارسال کرد هر المنتی رو که id داره میشه select کرد؟ برای اینکه در وقت صرفه جویی بشه میتونیم این پول ریکوئست رو ببندیم و از نقطه قبلی یه دونه برنچ ایجاد کنی فقط تایم رو اوکی کنی که لازم نباشه خودت هم وقت صرف برگردوندن به حالت اولیه کنی

اره حالا نه فقط id با کلاس هم میشه select کرد که قطعا میدونی
اوکی شد review زدم مشکلی داشت بگو

2023-11-12 08:30 UTC, majidbabakh commented on index.html
> +    <script defer src="app.js"></script>
گفتم که دلیلشوو

ببین وقتی defer نذاری همزمان فایل app.js و index.html دارن parse میشن
تو فایل app.js قسمتی هست که داره تگ p را select میکنه
از اون طرف html هنوز به تگ p نرسیده که parse ش کنه 
پس js میگه همچین تگی وجود دارد که من بخوام select ش کنم 
برا همین ی بیلاخ نشون میده و چیزی تو صفحه چاپ نمیکنه :)

2023-11-12 08:45 UTC, BCFCODE approved these changes
Good Job!

2023-11-12 08:45 UTC, BCFCODE commented on app.js
>  export { dateOfMeasurement };
آره این باید کامنت بشه اگر تست رو نمی خوای

2023-11-12 08:45 UTC, BCFCODE commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/e3899186-ec21-4826-acd3-8171f0dfe1a9)

یه نکته دیگه هم اینه که فقط بخش تایم رو می تونی داینامیک کنی، هارد کد رو بذاری داخل HTML بمونه
ببین میشه؟
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/24d6998e-d918-434c-8bdc-e959f8c96897)

منظور اینه آیا میشه این رو داخل HTML بذاریم بمونه؟ و فقط بخش داینامیک داخل app.js بیاد؟

2023-11-12 08:45 UTC, BCFCODE commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
> این که میگی اولویت فک نمیکنم اولویتی باشه innerHTML یه قابلیت اضافه داره نسبت به اون
> 
> textContents is all text contained by an element and all its children that are for formatting purposes only. innerText returns all text contained by an element and all its child elements. innerHtml returns all text, including html tags, that is contained by an element.

غلط نیست، چون مسئله حل شده، innerText چطور متداول تر نیست؟

2023-11-12 08:45 UTC, BCFCODE commented on app.js
>  export { dateOfMeasurement };
یه نکته دیگه هم اینکه وقتی تست فعال هست لاگ ات رو از کار می اندازه اینم حواست باشه
لاگ رو دیگه داخل browser inspect نمی بینی...

2023-11-12 08:45 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
Good job!
هر وقت لازم شد حتما ازش استفاده می کنیم

2023-11-12 08:45 UTC, BCFCODE commented on index.html
> +      <h2>
بله همینطوره
querySelector
آیا روش دیگه ای هم بلدی؟

2023-11-12 08:45 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
پس چرا بیلاخ به من نشون نمیده؟ :)

2023-11-12 08:45 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
نه آقا جان من درست میگی، من اشتباه کردم، و differ رو یاد گرفتم دمت گرم

2023-11-12 08:47 UTC, merged

2023-11-12 08:53 UTC, majidbabakh commented on index.html
> +      <h2>
غیر اینا چیزی خاطرم نیست
getElementById
getElementsByClassName
getElementsByTagName
querySelector
querySelectorAll
اولی و دو تا آخری استفاده میکنم

2023-11-12 08:54 UTC, majidbabakh commented on index.html
> +    <script defer src="app.js"></script>
> نه آقا جان من درست میگی، من اشتباه کردم، و differ رو یاد گرفتم دمت گرم

قربونت فقط defer نه differ :)

2023-11-12 08:55 UTC, majidbabakh commented on index.html
> +    <script defer src="app.js"></script>
> پس چرا بیلاخ به من نشون نمیده؟ :)

وقتی html زودتر parse کنه بیلاخو نشون نمیده طبیعتا :)

2023-11-12 08:55 UTC, BCFCODE commented on index.html
> +      <h2>
getElementsByClassName
جالبه تا الان استفاده نکردم شیک و تمیزتر بنظر می رسه

2023-11-12 08:57 UTC, majidbabakh commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
> > این که میگی اولویت فک نمیکنم اولویتی باشه innerHTML یه قابلیت اضافه داره نسبت به اون
> > textContents is all text contained by an element and all its children that are for formatting purposes only. innerText returns all text contained by an element and all its child elements. innerHtml returns all text, including html tags, that is contained by an element.
> 
> غلط نیست، چون مسئله حل شده، innerText چطور متداول تر نیست؟

تفاوتی توشون پیدا نکردم مهم خروجیه کاره 
البته که با react که کار میکنیم اینا دیگه مطرح نیس

2023-11-12 08:59 UTC, BCFCODE commented on index.html
> +    <script defer src="app.js"></script>
> > نه آقا جان من درست میگی، من اشتباه کردم، و differ رو یاد گرفتم دمت گرم
> 
> قربونت فقط defer نه differ :)

![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/de2f3429-133f-478c-b665-07ccd5fa1c6c)

فاک ایشو همین بود، غلط املایی :)

2023-11-12 09:00 UTC, majidbabakh commented on app.js
> +).textContent = `>>> ourFocusToDo Group 1000h speed Report > Date of
> ![image](https://user-images.githubusercontent.com/78473407/282286360-e3899186-ec21-4826-acd3-8171f0dfe1a9.png)
> 
> یه نکته دیگه هم اینه که فقط بخش تایم رو می تونی داینامیک کنی، هارد کد رو بذاری داخل HTML بمونه ببین میشه؟ ![image](https://user-images.githubusercontent.com/78473407/282286496-24d6998e-d918-434c-8bdc-e959f8c96897.png)
> 
> منظور اینه آیا میشه این رو داخل HTML بذاریم بمونه؟ و فقط بخش داینامیک داخل app.js بیاد؟

اون قسمتی که قراره داینامیک شه رو یه جوری بالاخره باید select ش کنم
حداقلش باید یه span بذاریم براش

2023-11-12 09:05 UTC, majidbabakh commented on index.html
> +      <h2>
> getElementsByClassName جالبه تا الان استفاده نکردم شیک و تمیزتر بنظر می رسه

برا select کردن المان تکی مناسب نیست خروجی array-like میده (HTMLCollection)
برای المان تکی بهترین گزینه querySelector هم کلاس و هم id میتونی select کنی

2023-11-12 09:11 UTC, BCFCODE commented on index.html
> +      <h2>
یروز چک می کنیم ببینیم دلیل وجودش چیه
remove any remote-tracking branches that no longer exist on the remote.
این برنچ حذف شد فرمان
git branch -d branch_name
بزن و لاگ بگیر حذف شده باشه روی لوکال ات