calculate currentHpd
BCFCODE/FocusToDo-Speed-Tracker pull request #56
Opened 2023-11-15 05:54 UTC by majidbabakh

اینم یکی دیگه ش

2023-11-15 06:28 UTC, BCFCODE commented
از این ببعد کسی که پول ریکوئست رو می فرسته بهتره وظیفه مشخص کردن این بخش ها رو هم داشته باشه
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/99a53ac5-3022-41c3-b37f-f6a501808e57)
As a convension...

2023-11-15 06:42 UTC, BCFCODE requested changes
دیتا بیس هم رسیدگی شود

2023-11-15 06:42 UTC, BCFCODE commented on app.js
> +  currentHpd(day) {
ورودی نباید بگیره 
ورودی مشخص هست
history[durationToReach1000h]
افزودن argument الزامی نیست

2023-11-15 06:42 UTC, BCFCODE commented on app.js
> +    const minsPerDay = (1000 * 60) / day;
بجای day از دیتابیس استفاده کن

2023-11-16 18:33 UTC, majidbabakh commented
شاخه currentHpd یه تغییری توش دادم یه نگاه بش بنداز نظرتو بگو

2023-11-16 19:26 UTC, BCFCODE commented
> شاخه currentHpd یه تغییری توش دادم و دوباره فرستادم یه نگاه بش بنداز نظرتو بگو

کو پس؟ @majidbabakh

2023-11-16 19:27 UTC, BCFCODE commented
> از این ببعد کسی که پول ریکوئست رو می فرسته بهتره وظیفه مشخص کردن این بخش ها رو هم داشته باشه ![image](https://user-images.githubusercontent.com/78473407/283023569-99a53ac5-3022-41c3-b37f-f6a501808e57.png) As a convension... @majidbabakh

ببین اینا رو من می تونم الان خودم اوکی کنم وقت کمتری هم میگیره ولی اوکی اش کن :)

2023-11-16 19:36 UTC, BCFCODE reviewed
چیزی ندیدم که، اگر موردی هست روی خط اش کامنت کن

2023-11-16 19:37 UTC, majidbabakh commented
همون قبلیو Re-request review زدم نیومد چیزی؟

2023-11-16 19:39 UTC, majidbabakh commented
دوباره فرستادم ببین چیزی اومد یا نه؟

2023-11-16 19:41 UTC, BCFCODE requested changes
تغییراتی که کامنت کرده بودم که تغییری نکرده، کدوم بخش تغییردادی؟ روش کامنت کن :)

2023-11-16 19:45 UTC, majidbabakh commented
> تغییراتی که کامنت کرده بودم که تغییری نکرده، کدوم بخش تغییردادی؟ روش کامنت کن :)

انگار push نشده 
میشه این pull request حذف کرد دوباره بفرستم؟

2023-11-16 19:47 UTC, closed without merging

2023-11-16 19:48 UTC, BCFCODE commented
> > تغییراتی که کامنت کرده بودم که تغییری نکرده، کدوم بخش تغییردادی؟ روش کامنت کن :)
> 
> انگار push نشده میشه این pull request حذف کرد دوباره بفرستم؟

بستیش که :) نمی دونم داری چ می کنی :)