calculate averageHourPerDay
BCFCODE/FocusToDo-Speed-Tracker pull request #73
Opened 2023-11-21 12:29 UTC by majidbabakh

این یه شبه کد فرضش کن 
کد نگاه کن ببین منظورتو درست متوجه شدم یا نه

2023-11-21 17:49 UTC, BCFCODE commented
> این یه شبه کد فرضش کن کد نگاه کن ببین منظورتو درست متوجه شدم یا نه

از شبه کد منظور چیه؟ اصطلاح متداولیه؟ @majidbabakh

2023-11-21 17:56 UTC, BCFCODE requested changes
ببین:
میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد
بعد این میره توی دیتا بیس سیو میشه
میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد
@majidbabakh

2023-11-21 17:56 UTC, BCFCODE commented
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/3cdbe29d-c260-4522-8887-e2f992013a55)
کار با این رو تمرین کن

2023-11-21 18:05 UTC, majidbabakh commented
> ![image](https://user-images.githubusercontent.com/78473407/284673123-3cdbe29d-c260-4522-8887-e2f992013a55.png) کار با این رو تمرین کن

رو pull request  تو میتونم request بزنم؟

2023-11-21 18:06 UTC, majidbabakh commented
> ![image](https://user-images.githubusercontent.com/78473407/284673123-3cdbe29d-c260-4522-8887-e2f992013a55.png) کار با این رو تمرین کن

با چی تمرین کنم؟

2023-11-21 20:42 UTC, BCFCODE commented
ینی دیگ پول جدید نده، روی همین ک درخواست تغییر دادم تغییر رو اعمال و...

2023-11-22 11:58 UTC, majidbabakh commented
> ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh

کدی که تا حالا نوشتی push کنم ببینم

2023-11-22 14:43 UTC, BCFCODE commented
> > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> 
> کدی که تا حالا نوشتی push کنم ببینم

جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
@majidbabakh

2023-11-22 14:59 UTC, majidbabakh commented
> > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > 
> > کدی که تا حالا نوشتی push کنم ببینم
> 
> جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> @majidbabakh 

 شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم
قولی که داده بودم روزی ۱ ساعت (که البته بیشتر  شد) وقت گذاشتم 
هنوز تموم نشده

2023-11-22 17:33 UTC, BCFCODE commented
> > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > 
> > > 
> > > کدی که تا حالا نوشتی push کنم ببینم
> > 
> > 
> > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > @majidbabakh
> 
> شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده

تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی
برو روی همون برنچ خودت بزن
git merge main
تا تغییرات رو روی برنچ ات مرج کنی
اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم
روی تو برای حل این چند مسئله حساب کردم
هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم
@majidbabakh

2023-11-22 17:35 UTC, BCFCODE commented
> > > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > 
> > > > 
> > > > کدی که تا حالا نوشتی push کنم ببینم
> > > 
> > > 
> > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > @majidbabakh
> > 
> > 
> > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> 
> تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh

فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی
یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد

2023-11-22 18:00 UTC, majidbabakh commented
> > > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > 
> > > > 
> > > > کدی که تا حالا نوشتی push کنم ببینم
> > > 
> > > 
> > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > @majidbabakh
> > 
> > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> 
> تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی
> برو روی همون برنچ خودت بزن
> git merge main
> تا تغییرات رو روی برنچ ات مرج کنی
> اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم
> روی تو برای حل این چند مسئله حساب کردم
> هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم
> @majidbabakh 

تایم گیت که جداست تایم js گذاشتم رو این

تغیراتتو گرفته بودم قبلا
چون گفتی موازی داری با من روش این قسمت کار میکنی گفتم تغییراتو پوش کن 

من قول میدم که روزی یکی دو ساعت روش وقت بذارم ولی قول نمیدم که رو ددلاینی که مشخص میکنی انجام بدم چون اولویتم فعلا خوندن چیزای پایه ایه که مدنظرمه

2023-11-22 18:08 UTC, majidbabakh commented
> > > > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > > 
> > > > > 
> > > > > کدی که تا حالا نوشتی push کنم ببینم
> > > > 
> > > > 
> > > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > > @majidbabakh
> > > 
> > > 
> > > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> > 
> > 
> > تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh
> 
> فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد

من خودمو با کسی مقایسه نمیکنم طبق شرایطی که دارم و زمانی که بدست میارم برا خوندن به بهترین شکل دارم کارمو جلو میبرم
اصلا ربطی نداره به این تیم یا هر تیم دیگه ای!

هدفمم الان گرفتن پروژه نبوده که بخام بگم با این شرایط میتونم از پس یه پروژه بر بیام یا نه
زمانی که اماده بشم شرایط به شکل دیگه خواهد بود قطعا
فعلا در حال حاضر وقتم محدود از طرف دیگه باید پایه مو درست کنم

2023-11-22 18:37 UTC, BCFCODE commented
> > > > > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > > > 
> > > > > > 
> > > > > > کدی که تا حالا نوشتی push کنم ببینم
> > > > > 
> > > > > 
> > > > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > > > @majidbabakh
> > > > 
> > > > 
> > > > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> > > 
> > > 
> > > تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh
> > 
> > 
> > فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد
> 
> من خودمو با کسی مقایسه نمیکنم طبق شرایطی که دارم و زمانی که بدست میارم برا خوندن به بهترین شکل دارم کارمو جلو میبرم اصلا ربطی نداره به این تیم یا هر تیم دیگه ای!
> 
> هدفمم الان گرفتن پروژه نبوده که بخام بگم با این شرایط میتونم از پس یه پروژه بر بیام یا نه زمانی که اماده بشم شرایط به شکل دیگه خواهد بود قطعا فعلا در حال حاضر وقتم محدود از طرف دیگه باید پایه مو درست کنم

امیدوارم چوب رو هم بذاری زمین و یکم خوش اخلاق هم بشی این همه میگم مثبت مثبت که نسبت به هر پیامی انقد واکنش سنگین نشون ندی پسر خوب، هر طور صلاح میدونی من دیگه دخالتی در برنامه هات نمی کنم
@majidbabakh

2023-11-22 19:32 UTC, majidbabakh commented
> > > > > > > > ببین: می> > > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > > > > 
> > > > > > > 
> > > > > > > کدی که تا حالا نوشتی push کنم ببینم
> > > > > > 
> > > > > > 
> > > > > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > > > > @majidbabakh
> > > > > 
> > > > > 
> > > > > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> > > > 
> > > > 
> > > > تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh
> > > 
> > > 
> > > فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد
> > 
> > 
> > من خودمو با کسی مقایسه نمیکنم طبق شرایطی که دارم و زمانی که بدست میارم برا خوندن به بهترین شکل دارم کارمو جلو میبرم اصلا ربطی نداره به این تیم یا هر تیم دیگه ای!
> > هدفمم الان گرفتن پروژه نبوده که بخام بگم با این شرایط میتونم از پس یه پروژه بر بیام یا نه زمانی که اماده بشم شرایط به شکل دیگه خواهد بود قطعا فعلا در حال حاضر وقتم محدود از طرف دیگه باید پایه مو درست کنم
> 
> امیدوارم چوب رو هم بذاری زمین و یکم خوش اخلاق هم بشی این همه میگم مثبت مثبت که نسبت به هر پیامی انقد واکنش سنگین نشون ندی پسر خوب، هر طور صلاح میدونی من دیگه دخالتی در برنامه هات نمی کنم، هر آنچه بهت میگم اگر مثبت بهش نگاه کنی چیزی جز انگیزه در وجودت ایجاد نمیشه هدفی هم جز این نداره... همینطور چشم اندازی که هر دو براش باید تلاش کنیم رو رسم کردم، در مورد سه روز... نه صرفا خودت، و توصیه اکید من اینه که بدونیم تعامل مثبت در اینه که حتی اگر منفی دریافت کردی مثبت بازتاب بدی، چه برسد به اینکه مثبت دریافت کنی اول باید حال ات خوب باشه @majidbabakh

مگه بداخلاقم؟
اگه رو حرفم برداشت سنگین حس میکنی شاید به خاطر اینکه متقابل سنگین دریافت میکنم
تو کار گروهی بهترین چیز گفتم حقیقته که افراد چیز بین خودشون نداشته باشن که بخوان هی برا خودشون بازگو کنن بزرگش کنن و به کینه تبدیل بشه
من متاسفانه تو گفتارت یه نگاه از بالا به پایین میبینم که میخای زیر دستت باشنن و برنامه ها تو ذهنت جلو بره و این طور نشون میدی که از همه بیشتر میدونی و بیشتر میفهمی و من باش راحت نیستم 
تو رفتارت اینطور به من نشون دادی نمیدونم چقد اینطور هسی یا نه
حالا میخای بگی غرور و احساسات و سربازی و نرفتی و اینا 


هدفمون یکیه و بخاطر موقعیت و  خصوصایت فکریمون مسیرمون کمی متفاوته من بارها قبلا گفتم که برنامه مم چیه درست یا غلط با ازمون خطای بسیار به این رسیدم و تغییر نمیکنه همونطور که تو روی برنامه ت هسی و داری انجامش میدی

اینا را مانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > > > > 
> > > > > > > 
> > > > > > > کدی که تا حالا نوشتی push کنم ببینم
> > > > > > 
> > > > > > 
> > > > > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > > > > @majidbabakh
> > > > > 
> > > > > 
> > > > > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> > > > 
> > > > 
> > > > تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh
> > > 
> > > 
> > > فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد
> > 
> > 
> > من خودمو با کسی مقایسه نمیکنم طبق شرایطی که دارم و زمانی که بدست میارم برا خوندن به بهترین شکل دارم کارمو جلو میبرم اصلا ربطی نداره به این تیم یا هر تیم دیگه ای!
> > هدفمم الان گرفتن پروژه نبوده که بخام بگم با این شرایط میتونم از پس یه پروژه بر بیام یا نه زمانی که اماده بشم شرایط به شکل دیگه خواهد بود قطعا فعلا در حال حاضر وقتم محدود از طرف دیگه باید پایه مو درست کنم
> 
> امیدوارم چوب رو هم بذاری زمین و یکم خوش اخلاق هم بشی این همه میگم مثبت مثبت که نسبت به هر پیامی انقد واکنش سنگین نشون ندی پسر خوب، هر طور صلاح میدونی من دیگه دخالتی در برنامه هات نمی کنم، هر آنچه بهت میگم اگر مثبت بهش نگاه کنی چیزی جز انگیزه در وجودت ایجاد نمیشه هدفی هم جز این نداره... همینطور چشم اندازی که هر دو براش باید تلاش کنیم رو رسم کردم، در مورد سه روز... نه صرفا خودت، و توصیه اکید من اینه که بدونیم تعامل مثبت در اینه که حتی اگر منفی دریافت کردی مثبت بازتاب بدی، چه برسد به اینکه مثبت دریافت کنی اول باید حال ات خوب باشه @majidbabakh

مگه بداخلاقم؟
اگه رو حرفم برداشت سنگین حس میکنی شاید به خاطر اینکه متقابل سنگین دریافت میکنم
تو کار گروهی بهترین چیز داشتن صداقته تا  افراد چیز بین خودشون نداشته باشن که بخوان هی برا خودشون بازگو کنن بزرگش کنن و به کینه تبدیل بشه
من متاسفانه تو گفتارت یه نگاه از بالا به پایین میبینم که میخای بقیه زیر دستت باشن و برنامه ها تو ذهنت جلو بره و این طور نشون میدی که از همه بیشتر میدونی و بیشتر میفهمی و من باش راحت نیستم 
تو رفتارت اینطور به من نشون دادی نمیدونم چقد اینطور هسی یا نه
حالا میخای بگی غرور و احساسات و سربازی و نرفتی و اینا بماند


هدفمون یکیه و بخاطر موقعیت و  خصوصایت فکریمون مسیرمون کمی متفاوته من بارها قبلا گفتم که برنامه مم چیه درست یا غلط با ازمون خطای بسیار به این رسیدم و تغییر نمیکنه و مهمترین چیز برام استمراره تو کاریه که هستم به طوری که اگه کار فعلیم مهم باشه و به کار مهمتری برخورم اولویت انجام کار مهمه همونطور که تو روی برنامه ت هسی و داری انجامش میدی

اینا را میگم که بعد با مشکل نخوریم شخصا دوست دارم برات ارزش قائلم و پشتکارتو تحسین میکنم ولی توی کار گروهی باید شرایط دو طرف برقرار باشه تا به یه جایی برسه

2023-11-22 19:43 UTC, BCFCODE commented
> > > > > > > > > ببین: می> > > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > > > > > > 
> > > > > > > > 
> > > > > > > > کدی که تا حالا نوشتی push کنم ببینم
> > > > > > > 
> > > > > > > 
> > > > > > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > > > > > @majidbabakh
> > > > > > 
> > > > > > 
> > > > > > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> > > > > 
> > > > > 
> > > > > تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh
> > > > 
> > > > 
> > > > فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد
> > > 
> > > 
> > > من خودمو با کسی مقایسه نمیکنم طبق شرایطی که دارم و زمانی که بدست میارم برا خوندن به بهترین شکل دارم کارمو جلو میبرم اصلا ربطی نداره به این تیم یا هر تیم دیگه ای!
> > > هدفمم الان گرفتن پروژه نبوده که بخام بگم با این شرایط میتونم از پس یه پروژه بر بیام یا نه زمانی که اماده بشم شرایط به شکل دیگه خواهد بود قطعا فعلا در حال حاضر وقتم محدود از طرف دیگه باید پایه مو درست کنم
> > 
> > 
> > امیدوارم چوب رو هم بذاری زمین و یکم خوش اخلاق هم بشی این همه میگم مثبت مثبت که نسبت به هر پیامی انقد واکنش سنگین نشون ندی پسر خوب، هر طور صلاح میدونی من دیگه دخالتی در برنامه هات نمی کنم، هر آنچه بهت میگم اگر مثبت بهش نگاه کنی چیزی جز انگیزه در وجودت ایجاد نمیشه هدفی هم جز این نداره... همینطور چشم اندازی که هر دو براش باید تلاش کنیم رو رسم کردم، در مورد سه روز... نه صرفا خودت، و توصیه اکید من اینه که بدونیم تعامل مثبت در اینه که حتی اگر منفی دریافت کردی مثبت بازتاب بدی، چه برسد به اینکه مثبت دریافت کنی اول باید حال ات خوب باشه @majidbabakh
> 
> مگه بداخلاقم؟ اگه رو حرفم برداشت سنگین حس میکنی شاید به خاطر اینکه متقابل سنگین دریافت میکنم تو کار گروهی بهترین چیز گفتم حقیقته که افراد چیز بین خودشون نداشته باشن که بخوان هی برا خودشون بازگو کنن بزرگش کنن و به کینه تبدیل بشه من متاسفانه تو گفتارت یه نگاه از بالا به پایین میبینم که میخای زیر دستت باشنن و برنامه ها تو ذهنت جلو بره و این طور نشون میدی که از همه بیشتر میدونی و بیشتر میفهمی و من باش راحت نیستم تو رفتارت اینطور به من نشون دادی نمیدونم چقد اینطور هسی یا نه حالا میخای بگی غرور و احساسات و سربازی و نرفتی و اینا
> 
> هدفمون یکیه و بخاطر موقعیت و خصوصایت فکریمون مسیرمون کمی متفاوته من بارها قبلا گفتم که برنامه مم چیه درست یا غلط با ازمون خطای بسیار به این رسیدم و تغییر نمیکنه همونطور که تو روی برنامه ت هسی و داری انجامش میدی
> 
> اینا را مانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> 
> > > > > > > > کدی که تا حالا نوشتی push کنم ببینم
> > > > > > > 
> > > > > > > 
> > > > > > > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > > > > > > @majidbabakh
> > > > > > 
> > > > > > 
> > > > > > شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده
> > > > > 
> > > > > 
> > > > > تایمی که میذاری رو فقط گیت حساب نکن، چون فقط همون لحظه ای که چند تا فرمان برای پوش و ... میدی گیت حساب میشه، بقیه اش اصل برنامه نویسی و تمرین و حل مسئله و پروژه است، من 4 تا از 5 تا سرتیفیکیشن فری کد کمپ رو پاس کردم، آخری حسابی گیرم انداخته، این دو روز روزی 4ساعت گیرشم (فقط این بخش) شاخه main اگر پول کنی تغییرات قابل ارائه که اضافه کردن پوشه های جدید برای separation of concern هست رو که دادم می بینی برو روی همون برنچ خودت بزن git merge main تا تغییرات رو روی برنچ ات مرج کنی اما پوشه ها خالی هستن، از همین نقطه برنچ جدیدی ایجاد کردم و روی اون دارم تغییرات رو اعمال می کنم روی تو برای حل این چند مسئله حساب کردم هنوز وقت روی این بخشی که توی گیت هاب مطرح شده داری روش کار می کنی نذاشتم @majidbabakh
> > > > 
> > > > 
> > > > فقط ازت خواهش می کنم زیر 8 ساعت نیا چون اصلا توی تیم ما جواب نیس! فک کن بعد از 2 سال از غار اومدم بیرون سفر دیگه میبینی ساعتمو، می دونم داری تمام تلاش تو می کنی و مطمئنم بیشترش هم می کنی یک پروژه این چنینی رو وقتی در عرض نهایتا سه روز تمام کردیم اونوقت میشه روی پروژه گرفتن و... حساب کرد
> > > 
> > > 
> > > من خودمو با کسی مقایسه نمیکنم طبق شرایطی که دارم و زمانی که بدست میارم برا خوندن به بهترین شکل دارم کارمو جلو میبرم اصلا ربطی نداره به این تیم یا هر تیم دیگه ای!
> > > هدفمم الان گرفتن پروژه نبوده که بخام بگم با این شرایط میتونم از پس یه پروژه بر بیام یا نه زمانی که اماده بشم شرایط به شکل دیگه خواهد بود قطعا فعلا در حال حاضر وقتم محدود از طرف دیگه باید پایه مو درست کنم
> > 
> > 
> > امیدوارم چوب رو هم بذاری زمین و یکم خوش اخلاق هم بشی این همه میگم مثبت مثبت که نسبت به هر پیامی انقد واکنش سنگین نشون ندی پسر خوب، هر طور صلاح میدونی من دیگه دخالتی در برنامه هات نمی کنم، هر آنچه بهت میگم اگر مثبت بهش نگاه کنی چیزی جز انگیزه در وجودت ایجاد نمیشه هدفی هم جز این نداره... همینطور چشم اندازی که هر دو براش باید تلاش کنیم رو رسم کردم، در مورد سه روز... نه صرفا خودت، و توصیه اکید من اینه که بدونیم تعامل مثبت در اینه که حتی اگر منفی دریافت کردی مثبت بازتاب بدی، چه برسد به اینکه مثبت دریافت کنی اول باید حال ات خوب باشه @majidbabakh
> 
> مگه بداخلاقم؟ اگه رو حرفم برداشت سنگین حس میکنی شاید به خاطر اینکه متقابل سنگین دریافت میکنم تو کار گروهی بهترین چیز داشتن صداقته تا افراد چیز بین خودشون نداشته باشن که بخوان هی برا خودشون بازگو کنن بزرگش کنن و به کینه تبدیل بشه من متاسفانه تو گفتارت یه نگاه از بالا به پایین میبینم که میخای بقیه زیر دستت باشن و برنامه ها تو ذهنت جلو بره و این طور نشون میدی که از همه بیشتر میدونی و بیشتر میفهمی و من باش راحت نیستم تو رفتارت اینطور به من نشون دادی نمیدونم چقد اینطور هسی یا نه حالا میخای بگی غرور و احساسات و سربازی و نرفتی و اینا بماند
> 
> هدفمون یکیه و بخاطر موقعیت و خصوصایت فکریمون مسیرمون کمی متفاوته من بارها قبلا گفتم که برنامه مم چیه درست یا غلط با ازمون خطای بسیار به این رسیدم و تغییر نمیکنه و مهمترین چیز برام استمراره تو کاریه که هستم به طوری که اگه کار فعلیم مهم باشه و به کار مهمتری برخورم اولویت انجام کار مهمه همونطور که تو روی برنامه ت هسی و داری انجامش میدی
> 
> اینا را میگم که بعد با مشکل نخوریم شخصا دوست دارم برات ارزش قائلم و پشتکارتو تحسین میکنم ولی توی کار گروهی باید شرایط دو طرف برقرار باشه تا به یه جایی برسه

چون خودمم شرایط مشابه دارم فشاری نیاوردم، در مورد نگاه بالا به پایین و...، قبلا فک کنم راجع بهش صحبت کردیم و تصور کردم این ذهنیت ها حل شده باشه... 
@majidbabakh

2023-11-23 16:15 UTC, BCFCODE commented
> > > > ببین: میانگین Hpd فعلی و Hpd قبلی رو می خواد که از جمع زدن همین دوتا فقط و تقسیم بر تعداد کردن اش بدست میاد بعد این میره توی دیتا بیس سیو میشه میان گین بعدی فقط از جمع زدن این با میان گین قبلی و تقسیم بر دوش بدست میاد @majidbabakh
> > > 
> > > 
> > > کدی که تا حالا نوشتی push کنم ببینم
> > 
> > 
> > جمله ات مشخص نیست دقیقا چی خواستی؟ تغییری هنوز از سمت ات نیومده
> > @majidbabakh
> 
> شاخه ای که مربوط به خودته و داری روش کار میکنی push کن تغییراتتو ببینم قولی که داده بودم روزی ۱ ساعت (که البته بیشتر شد) وقت گذاشتم هنوز تموم نشده

تنظیم اش کردم که حتی اگر خودمم بخوام روی شاخه اصلی مرج کنم یک روویو از سمت اعضای تیم لازم داشته باشه، به محض اینکه تمام بشه وآماده مرج میفرستم و خودت تایید تا نکنی مرج نمیشه 
@majidbabakh

2023-11-23 18:58 UTC, majidbabakh commented
یه تغییر رو currentHourPerDay ببین همونه که میخای یا نه

2023-11-25 06:47 UTC, majidbabakh commented
> یه تغییر رو currentHourPerDay ببین همونه که میخای یا نه تغییرات رو همون کامیت قبلی اعمال کردم و به صورت force پوشش کردم

؟

2023-11-25 07:16 UTC, BCFCODE commented
> > یه تغییر رو currentHourPerDay ببین همونه که میخای یا نه تغییرات رو همون کامیت قبلی اعمال کردم و به صورت force پوشش کردم
> 
> ؟

سرتیفیکیشن ها حسابی درگیرم کرده @majidbabakh 
دنبال فرصتم

2023-11-25 08:16 UTC, BCFCODE commented
> > > یه تغییر رو currentHourPerDay ببین همونه که میخای یا نه تغییرات رو همون کامیت قبلی اعمال کردم و به صورت force پوشش کردم
> > 
> > 
> > ؟
> 
> سرتیفیکیشن ها حسابی درگیرم کرده @majidbabakh دنبال فرصتم

در مورد فورس پوش و تغییر روی کامیت قبلی یه توضیح بده، چرا از این گزینه ها استفاده کردی؟ در مورد ممنوعه بودن فورس پوش مطلعی؟

2023-11-25 09:48 UTC, majidbabakh commented
> > > > یه تغییر رو currentHourPerDay ببین همونه که میخای یا نه تغییرات رو همون کامیت قبلی اعمال کردم و به صورت force پوشش کردم
> > > 
> > > 
> > > ؟
> > 
> > 
> > سرتیفیکیشن ها حسابی درگیرم کرده @majidbabakh دنبال فرصتم
> 
> در مورد فورس پوش و تغییر روی کامیت قبلی یه توضیح بده، چرا از این گزینه ها استفاده کردی؟ در مورد ممنوعه بودن فورس پوش مطلعی؟

تغییرو به کامیت قبلی اضافه کردم حواسم نبود کامیت قبلیو پوش کرده بودم دیگه زورکی پوشش کردم
باید کامیت جدا پوش میکردم مرج کردنشو میذاشتم به عهده تو

2023-11-25 11:36 UTC, BCFCODE commented
> > > > > یه تغییر رو currentHourPerDay ببین همونه که میخای یا نه تغییرات رو همون کامیت قبلی اعمال کردم و به صورت force پوشش کردم
> > > > 
> > > > 
> > > > ؟
> > > 
> > > 
> > > سرتیفیکیشن ها حسابی درگیرم کرده @majidbabakh دنبال فرصتم
> > 
> > 
> > در مورد فورس پوش و تغییر روی کامیت قبلی یه توضیح بده، چرا از این گزینه ها استفاده کردی؟ در مورد ممنوعه بودن فورس پوش مطلعی؟
> 
> تغییرو به کامیت قبلی اضافه کردم حواسم نبود کامیت قبلیو پوش کرده بودم دیگه زورکی پوشش کردم باید کامیت جدا پوش میکردم مرج کردنشو میذاشتم به عهده تو

دقیق نمی تونم تصور کنم چکار کردی :) ولی چک می کنم ببینم چ کردی @majidbabakh

2023-11-25 21:25 UTC, BCFCODE requested changes
کد ات رو چک کردم 
چند سوال نوشتم

2023-11-25 21:31 UTC, BCFCODE reviewed
یه سری سوال رو برای مرور روی کد ها نوشتم

2023-11-25 21:31 UTC, BCFCODE commented on index.js
> +    for (let i = 0; i <= historyData.length - 1; i++) {
چرا لوپ؟

2023-11-25 21:31 UTC, BCFCODE commented on index.js
> +    for (let i = 1; i <= historyData.length - 1; i++) {
همین طور اینجا برای محاسبه میانگین...

2023-11-25 21:31 UTC, BCFCODE commented on index.js
> +        historyData[i].currentHourPerDay[0],
میانگین هارد کد شده درسته؟ ینی با بزرگ شدن دیتا بیس بصورت خودکار انجامش نمیده؟
در واقع ایندکس صفر و یک هارد کد شده، در حالی که دیتا بیس بصورت داینامیک داره دیتا رو سیو می کنه و ممکنه مثلا تا ایندکس ده هم داشته باشیم و بعد اونموقع این کد چطوری از پس اش بر میاد؟ (ایندکس صفر و یک منظورمه)

2023-11-25 21:36 UTC, BCFCODE commented
روی همین شاخه یدونه 
git merge main 
رو بزن و تغییرات جدید رو بگیر
یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه
ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه

2023-11-25 21:39 UTC, BCFCODE commented
اگر جایی رو درست ممتوجه نشدم روی خط اش برام بنویس

2023-11-26 03:21 UTC, majidbabakh commented on index.js
> +    for (let i = 0; i <= historyData.length - 1; i++) {
> چرا لوپ؟

مقدار هر ایندکس جدا جدا میخوای محاسبه کنی؟

2023-11-26 03:25 UTC, majidbabakh commented on index.js
> +        historyData[i].currentHourPerDay[0],
> میانگین هارد کد شده درسته؟ ینی با بزرگ شدن دیتا بیس بصورت خودکار انجامش نمیده؟ در واقع ایندکس صفر و یک هارد کد شده، در حالی که دیتا بیس بصورت داینامیک داره دیتا رو سیو می کنه و ممکنه مثلا تا ایندکس ده هم داشته باشیم و بعد اونموقع این کد چطوری از پس اش بر میاد؟ (ایندکس صفر و یک منظورمه)

منم گیرم همین بود الان این یک ماه مشخص حساب میکنه
کدای قبلی که نوشتی هارد کد بود منم به همون منوال رفتم جلو

برای محاسبه یک ماه که هارد کد نیست ایندکس صفر با این فرض حسابش نکردم که ماه قبلی برای نداریم اگه ام داشتیم چون اصلا ماه داینامیک نشده پس در حالت هارد کده

2023-11-26 03:26 UTC, majidbabakh commented
> روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه

البته UI در لحظه همه را قرار نیست محاسبه کنه هر ایندکسی که ثبت شده بود همونو محاسبه میکنه

2023-11-26 03:36 UTC, majidbabakh commented
> روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه

چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم

2023-11-26 04:00 UTC, BCFCODE commented on index.js
> +    for (let i = 0; i <= historyData.length - 1; i++) {
> > چرا لوپ؟
> 
> مقدار هر ایندکس جدا جدا میخوای محاسبه کنی؟

هر بار که فانکشن کال میشه، یک بار ساعت در ساعت و ساعت در روز جاری رو محاسبه می کنه (کاری به قبلیا نداره) اونا توی دیتابیس هستن و قبلا محاسبه شدن (حداقل الان به چنین محاسبه ای نیاز نداریم
و همین طور میانگین قبلی و فعلی

2023-11-26 04:01 UTC, BCFCODE commented on index.js
> +        historyData[i].currentHourPerDay[0],
مشکلی نیست
یکی از راه های فهم مسئله هم همینه
به مرور با همین تجربیات سرعت اش افزایش پیدا می کنه

2023-11-26 04:03 UTC, BCFCODE commented
> > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> 
> چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم

ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟
اما اگر مسئله دیگه ای هست بهم بگو

2023-11-26 04:05 UTC, BCFCODE commented
البته یه تکنیک هست که سرعت نمایش یو آی رو بالا می بره که مث الان فوکاس تو دو نشه که برای هر چیز کوچیک، اپ مجبور به ارتباط با سرور و دیتابیس و متحمل شدن زمان برای نمایش به کاربر بشه، احتمال داره روزی برای حل یا پیشگیری از این مشکل آگاهانه تصمیم بگیریم همین کاری که کردی، (محاسبه در یو آی) رو توی اپ انجام بدیم به روش های دیگه
@majidbabakh

2023-11-26 06:16 UTC, majidbabakh commented
> > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > 
> > 
> > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> 
> ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو

نه از این قسمت روانشناسی بیا بیرون

من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری
و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی 
یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه 

اینو مشخص کن 
چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی
بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم

2023-11-26 07:38 UTC, BCFCODE commented
> > > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > > 
> > > 
> > > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> > 
> > 
> > ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو
> 
> نه از این قسمت روانشناسی بیا بیرون
> 
> من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه
> 
> اینو مشخص کن چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم

ببین من خسته شدم از پاک کردن پیام ها، دوباره نرو جاده خاکی، کاملا مسئله مشخصه، هر سوالی هم بپرسی دارم جواب میدم، منظورت از روانشناسی هم نمی دونم چیه من روانشناس نیستم، دائم داری میگی مشخص کن من ده صفحه تا الان متن نوشتم تا الان، یه نقشه دراز مدت میخوای که مو به مو همه چیز تا سن ده سالگی پروژه توش معلوم باشه باید بری گوگل کار کنی، هیچ جا ندیدم همچین چیزی، این پروژه هم خیلی ساده است واقعا نمی دونم دیگه چه چیزی رو باید واست مشخص کنم، پیام ها رو لطفا قبل از ارسال بررسی کن که وارد حاشیه نشیم، الانم یه برنچ جدید ساختم اونم یه مسئله است، سعی می کنم برنچ های مختلف از بخش های مختلف ایجاد کنم که هر کدوم که راحت بودی حل کنی @majidbabakh

2023-11-26 07:47 UTC, BCFCODE commented
> > > > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > > > 
> > > > 
> > > > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> > > 
> > > 
> > > ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو
> > 
> > 
> > نه از این قسمت روانشناسی بیا بیرون
> > من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه
> > اینو مشخص کن چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم
> 
> ببین من خسته شدم از پاک کردن پیام ها، دوباره نرو جاده خاکی، کاملا مسئله مشخصه، هر سوالی هم بپرسی دارم جواب میدم، منظورت از روانشناسی هم نمی دونم چیه من روانشناس نیستم، دائم داری میگی مشخص کن من ده صفحه تا الان متن نوشتم تا الان، یه نقشه دراز مدت میخوای که مو به مو همه چیز تا سن ده سالگی پروژه توش معلوم باشه باید بری گوگل کار کنی، هیچ جا ندیدم همچین چیزی، این پروژه هم خیلی ساده است واقعا نمی دونم دیگه چه چیزی رو باید واست مشخص کنم، پیام ها رو لطفا قبل از ارسال بررسی کن که وارد حاشیه نشیم، الانم یه برنچ جدید ساختم اونم یه مسئله است، سعی می کنم برنچ های مختلف از بخش های مختلف ایجاد کنم که هر کدوم که راحت بودی حل کنی @majidbabakh

این که همه چیز رو ایده آل و توی چارچوب می خوای و تا مشخص نشه نمیتونی کار رو جلو ببری ترمز سنگینیه، بشدت کند کننده است، اگر صلاح دونستی حل اش کن اگرم نه که نهایتا من می فرستم تو رویو کن تایید کن مرج بشه، بازم هر سوالی هست بصورت جزئی اطلاعاتی که لازم داری رو بپرس تا من بهت بدم

2023-11-26 07:49 UTC, BCFCODE commented
> > > > > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > > > > 
> > > > > 
> > > > > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> > > > 
> > > > 
> > > > ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو
> > > 
> > > 
> > > نه از این قسمت روانشناسی بیا بیرون
> > > من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه
> > > اینو مشخص کن چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم
> > 
> > 
> > ببین من خسته شدم از پاک کردن پیام ها، دوباره نرو جاده خاکی، کاملا مسئله مشخصه، هر سوالی هم بپرسی دارم جواب میدم، منظورت از روانشناسی هم نمی دونم چیه من روانشناس نیستم، دائم داری میگی مشخص کن من ده صفحه تا الان متن نوشتم تا الان، یه نقشه دراز مدت میخوای که مو به مو همه چیز تا سن ده سالگی پروژه توش معلوم باشه باید بری گوگل کار کنی، هیچ جا ندیدم همچین چیزی، این پروژه هم خیلی ساده است واقعا نمی دونم دیگه چه چیزی رو باید واست مشخص کنم، پیام ها رو لطفا قبل از ارسال بررسی کن که وارد حاشیه نشیم، الانم یه برنچ جدید ساختم اونم یه مسئله است، سعی می کنم برنچ های مختلف از بخش های مختلف ایجاد کنم که هر کدوم که راحت بودی حل کنی @majidbabakh
> 
> این که همه چیز رو ایده آل و توی چارچوب می خوای و تا مشخص نشه نمیتونی کار رو جلو ببری ترمز سنگینیه، بشدت کند کننده است، اگر صلاح دونستی حل اش کن اگرم نه که نهایتا من می فرستم تو رویو کن تایید کن مرج بشه، بازم هر سوالی هست بصورت جزئی اطلاعاتی که لازم داری رو بپرس تا من بهت بدم

اگر می دونی کلا من چیزی رو دارم خارج از قاعده و چارچوب پیش می برم اونم واضح مشخص کن تا اگر بتونم حل کنم، بهرحال با کمتر از این اطلاعات پروژه ها داره پیش میره، واقعا اعضای تیم روی یک مسئله انقد بحث و گفت و گو نمی کنند اما بازم اوکیه تا بالاخره از این حالت سکون و اسطکاک خارج بشه داستان، بهر حال هر کمکی و سوالی هست در خدمتم

2023-11-26 08:02 UTC, BCFCODE commented
> > > > > > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > > > > > 
> > > > > > 
> > > > > > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> > > > > 
> > > > > 
> > > > > ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو
> > > > 
> > > > 
> > > > نه از این قسمت روانشناسی بیا بیرون
> > > > من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه
> > > > اینو مشخص کن چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم
> > > 
> > > 
> > > ببین من خسته شدم از پاک کردن پیام ها، دوباره نرو جاده خاکی، کاملا مسئله مشخصه، هر سوالی هم بپرسی دارم جواب میدم، منظورت از روانشناسی هم نمی دونم چیه من روانشناس نیستم، دائم داری میگی مشخص کن من ده صفحه تا الان متن نوشتم تا الان، یه نقشه دراز مدت میخوای که مو به مو همه چیز تا سن ده سالگی پروژه توش معلوم باشه باید بری گوگل کار کنی، هیچ جا ندیدم همچین چیزی، این پروژه هم خیلی ساده است واقعا نمی دونم دیگه چه چیزی رو باید واست مشخص کنم، پیام ها رو لطفا قبل از ارسال بررسی کن که وارد حاشیه نشیم، الانم یه برنچ جدید ساختم اونم یه مسئله است، سعی می کنم برنچ های مختلف از بخش های مختلف ایجاد کنم که هر کدوم که راحت بودی حل کنی @majidbabakh
> > 
> > 
> > این که همه چیز رو ایده آل و توی چارچوب می خوای و تا مشخص نشه نمیتونی کار رو جلو ببری ترمز سنگینیه، بشدت کند کننده است، اگر صلاح دونستی حل اش کن اگرم نه که نهایتا من می فرستم تو رویو کن تایید کن مرج بشه، بازم هر سوالی هست بصورت جزئی اطلاعاتی که لازم داری رو بپرس تا من بهت بدم
> 
> اگر می دونی کلا من چیزی رو دارم خارج از قاعده و چارچوب پیش می برم اونم واضح مشخص کن تا اگر بتونم حل کنم، بهرحال با کمتر از این اطلاعات پروژه ها داره پیش میره، واقعا اعضای تیم روی یک مسئله انقد بحث و گفت و گو نمی کنند اما بازم اوکیه تا بالاخره از این حالت سکون و اسطکاک خارج بشه داستان، بهر حال هر کمکی و سوالی هست در خدمتم

نکته و یک پیشنهاد دیگه: یک پروژه خیلی خیلی ساده که یک روزه تمام بشه باز کن من رو دعوت کن داخل اش، اونجا مدیریت رو بهم یاد بده بگو باید اینجوری پروژه رو پیش ببری، و انتظار من اینه که این چیزها رو در اختیارم بذاری و همونا رو در اختیارم بذار کمک ات کنم تمام شه، من میشم تو تو بشو من... که بدونم دقیقا چی می خوای، اگرم کتاب خاصی راجع به این خوندی یا مطلبی هست که بلد نیستم، یا جایی مدیریت موثر تری دیدی دقیق و واضح منبع رو معرفی کن برم بخونم یاد بگیرم، در غیر این صورت، تمام اش کنیم اینو، یکی از اهداف اصلی من از این پروژه و دعوت ات این هست محاسبه کنم تمام کردن یک پروژه با تو برای من چقدر هزینه زمانی و ... داره، همینطور همین اطلاعات در مورد من دستت بیاد که حساب کار برای انجام یا عدم انجام پروژه های جدی تر دست مون بیاد، دیگ اصلا هیچ هدف دیگه ای به ذهنم نمی رسه که نگفته باشم مگر اینکه انتظار داشته باشی بشینم بسازم یه هدف دیگه :)

2023-11-26 10:07 UTC, majidbabakh commented
> > > > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > > > 
> > > > 
> > > > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> > > 
> > > 
> > > ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو
> > 
> > 
> > نه از این قسمت روانشناسی بیا بیرون
> > من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه
> > اینو مشخص کن چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم
> 
> ببین من خسته شدم از پاک کردن پیام ها، دوباره نرو جاده خاکی، کاملا مسئله مشخصه، هر سوالی هم بپرسی دارم جواب میدم، منظورت از روانشناسی هم نمی دونم چیه من روانشناس نیستم، دائم داری میگی مشخص کن من ده صفحه تا الان متن نوشتم تا الان، یه نقشه دراز مدت میخوای که مو به مو همه چیز تا سن ده سالگی پروژه توش معلوم باشه باید بری گوگل کار کنی، هیچ جا ندیدم همچین چیزی، این پروژه هم خیلی ساده است واقعا نمی دونم دیگه چه چیزی رو باید واست مشخص کنم، پیام ها رو لطفا قبل از ارسال بررسی کن که وارد حاشیه نشیم، الانم یه برنچ جدید ساختم اونم یه مسئله است، سعی می کنم برنچ های مختلف از بخش های مختلف ایجاد کنم که هر کدوم که راحت بودی حل کنی @majidbabakh

مرتضی جان پروژه رو خودت جلو ببر وقتمون گرفته نشه 
گویا حرف همو متوجه نمیشیم 

من اصلا در مورد مدیریت پروژه حرف نمیزنم که هی حرف از مدیریت میزنی
در مورد طراحی ام  که گفتی در مورد مهندسی نرم افزار بخون (نحوه تحلیل و طراحی نرم افزار در واقع قبل کدنویسی انجام میشه، کدنویسی آسونترین بخش ساخت نرم افزاره که من خودمم خیلی ازش نمیدونم  )
و در ضمن پایان همه پروژه ها بازه فقط پروژه تو نیست و کوچیکی و بزرگی پروژه مطرح نیست ، تو پروژه های کوچیک بعضی مراحلش اسکیپ میشه

یه پروژه را میشه همین طوری نوشت ولی بعدا چندین برابر باید براش وقت و انرژی بذاری چون هی برمیگردی بخشای قبل دوباره تغییر ایجاد میکنی
وسط کار متوجه میشی اگه مثلا ساختار history این شکلی بود بهتر بود ....

2023-11-26 10:25 UTC, BCFCODE commented
> > > > > > روی همین شاخه یدونه git merge main رو بزن و تغییرات جدید رو بگیر یکی از بهترین راه های تقویت حل مسئله حل کردن اش از راه های مختلفه ببین می تونی بدون اضافه کردن هیچ متد دیگه ای به کلاس اصلی حل اش کنی، بدون استفاده از لوپ، چون هر بار که محاسبه انجام میشه توی دیتا بیس ذخیره میشه، اینجور نیست که یو آی بخواد در لحظه تمام اش رو محاسبه کنه
> > > > > 
> > > > > 
> > > > > چون اصلا نمیدونم میخای چیکار کنی هیچ ایده ای براش ندارم
> > > > 
> > > > 
> > > > ببین مثل یک مسئله مطرح شده، و چندین بار نوشتمش برات، منتهی الان ذهن ات در حال پردازشه! از اول تا الان یک صحبت رو دارم انجام میدم و سعی داری متوجه اش بشی این دقیقا روند حل مسئله است، و بنظر طبیعی و قابل بهبود میاد، حس می کنی توی این مرحله می مونی و ازش عبور نمی کنی؟ اما اگر مسئله دیگه ای هست بهم بگو
> > > 
> > > 
> > > نه از این قسمت روانشناسی بیا بیرون
> > > من میگم کدی که نوشتی تو محاسباتت داری ماهو به صورت هارد کد میگیری و من نمیدونم چطوری میخای برنامه را جلو ببری یا میدونی میخای چیکار کنی و دوست داری مرحله به مرحله بگی یا فعلا یه نمونه میخای داشته باشی ببینی چی میشه
> > > اینو مشخص کن چیزی که من دارم میبینم برا گرفتن خروجی بعضی کارها دستی انجام میشه از محاسبه روز تا زمان رسیدن به 1000 ساعت بعدی بعد زمانو به برنامه میدی اون برات یکسری المانا را محاسبه میکنه ولی کدا براساس یک ماه مشخصه مثلا ماه یازدهم و این نمیخونه باهم
> > 
> > 
> > ببین من خسته شدم از پاک کردن پیام ها، دوباره نرو جاده خاکی، کاملا مسئله مشخصه، هر سوالی هم بپرسی دارم جواب میدم، منظورت از روانشناسی هم نمی دونم چیه من روانشناس نیستم، دائم داری میگی مشخص کن من ده صفحه تا الان متن نوشتم تا الان، یه نقشه دراز مدت میخوای که مو به مو همه چیز تا سن ده سالگی پروژه توش معلوم باشه باید بری گوگل کار کنی، هیچ جا ندیدم همچین چیزی، این پروژه هم خیلی ساده است واقعا نمی دونم دیگه چه چیزی رو باید واست مشخص کنم، پیام ها رو لطفا قبل از ارسال بررسی کن که وارد حاشیه نشیم، الانم یه برنچ جدید ساختم اونم یه مسئله است، سعی می کنم برنچ های مختلف از بخش های مختلف ایجاد کنم که هر کدوم که راحت بودی حل کنی @majidbabakh
> 
> مرتضی جان پروژه رو خودت جلو ببر وقتمون گرفته نشه گویا حرف همو متوجه نمیشیم
> 
> من اصلا در مورد مدیریت پروژه حرف نمیزنم که هی حرف از مدیریت میزنی در مورد طراحی ام که گفتی در مورد مهندسی نرم افزار بخون (نحوه تحلیل و طراحی نرم افزار در واقع قبل کدنویسی انجام میشه، کدنویسی آسونترین بخش ساخت نرم افزاره که من خودمم خیلی ازش نمیدونم ) و در ضمن پایان همه پروژه ها بازه فقط پروژه تو نیست و کوچیکی و بزرگی پروژه مطرح نیست ، تو پروژه های کوچیک بعضی مراحلش اسکیپ میشه
> 
> یه پروژه را میشه همین طوری نوشت ولی بعدا چندین برابر باید براش وقت و انرژی بذاری چون هی برمیگردی بخشای قبل دوباره تغییر ایجاد میکنی وسط کار متوجه میشی اگه مثلا ساختار history این شکلی بود بهتر بود ....

خدا پدرتم بیامرزه، دقیقا همینه که میگی، بله من اطلاعاتم کمه، انشاالله بمرور یادمیگیریم، یه دو سال پیش یه دوره خریدم 8 میلیون اینا رو توش گفته بود هنوزم دارم مرور می کنم و تمام سعی ام اینه که به بهترین شکل همه چیز جلو بره، نهایت تلاش من تا این لحظه رو داری می بینی، از هر آنچه بلدم دارم استفاده می کنم سعی می کنم به توهم یاد بدم با سخاوت... از توهم یاد بگیرم و .... پروژه بزنی میام باهات تمرین می کنم، مدیریت کنی پیروی می کنم، هر کاری کنی مربوط به برنامه نویسی پایه تم، واقعا هم سعی دارم درک ات کنم تیم بسازم نشد هم دیگه ضعف از من بوده و مسئولیت اش رو می پذیرم، دیگه مجبورم توی تیم یکی دیگه کار کنم، دیگه از این بدتر که نیست

2023-11-30 03:24 UTC, closed without merging